/*
 
 
 */

/*
 * FindReplaceDialog.java
 *
 * Created on 08.feb.2011, 14:55:27
 */

package motiflab.gui;

/**
 *
 * @author Kjetil
 */
public class FindReplaceDialog extends javax.swing.JDialog {
    Searchable panel;
    MotifLabGUI gui;
    boolean oldCaseSensitivitySetting=false;
    int replacecount=0;
    RecordingCompoundEdit undoableEdit;

    /** Creates new form FindReplaceDialog */
    public FindReplaceDialog(Searchable panel, MotifLabGUI gui) {
        super(gui.getFrame(), "Replace", true);
        this.panel=panel;
        this.gui=gui;
        initComponents();
        oldCaseSensitivitySetting=panel.isSearchCaseSensitive();
        caseSensitiveCheckbox.setSelected(false);
        pack();
        panel.setSearchIsCaseSensitive(caseSensitiveCheckbox.isSelected());
        panel.find(null); // this will reset search in the panel     
        undoableEdit=new RecordingCompoundEdit("replace");
        gui.getUndoManager().forwardUndoEvents(undoableEdit);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonspanel = new javax.swing.JPanel();
        leftButtonsPane = new javax.swing.JPanel();
        findNextButton = new javax.swing.JButton();
        replaceButton = new javax.swing.JButton();
        ReplaceAllButton = new javax.swing.JButton();
        rightButtonsPanel = new javax.swing.JPanel();
        CloseButton = new javax.swing.JButton();
        mainpanel = new javax.swing.JPanel();
        internalPanel = new javax.swing.JPanel();
        findLabel = new javax.swing.JLabel();
        replaceLabel = new javax.swing.JLabel();
        findTextfield = new javax.swing.JTextField();
        replaceTextfield = new javax.swing.JTextField();
        caseSensitiveCheckbox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        buttonspanel.setMinimumSize(new java.awt.Dimension(352, 38));
        buttonspanel.setName("buttonspanel"); // NOI18N
        buttonspanel.setPreferredSize(new java.awt.Dimension(400, 38));
        buttonspanel.setLayout(new java.awt.BorderLayout());

        leftButtonsPane.setName("leftButtonsPane"); // NOI18N
        leftButtonsPane.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5));

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(motiflab.gui.MotifLabApp.class).getContext().getResourceMap(FindReplaceDialog.class);
        findNextButton.setText(resourceMap.getString("findNextButton.text")); // NOI18N
        findNextButton.setName("findNextButton"); // NOI18N
        findNextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findNextButtonPressed(evt);
            }
        });
        leftButtonsPane.add(findNextButton);

        replaceButton.setText(resourceMap.getString("replaceButton.text")); // NOI18N
        replaceButton.setName("replaceButton"); // NOI18N
        replaceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replaceButtonPressed(evt);
            }
        });
        leftButtonsPane.add(replaceButton);

        ReplaceAllButton.setText(resourceMap.getString("ReplaceAllButton.text")); // NOI18N
        ReplaceAllButton.setName("ReplaceAllButton"); // NOI18N
        ReplaceAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReplaceAllButtonPressed(evt);
            }
        });
        leftButtonsPane.add(ReplaceAllButton);

        buttonspanel.add(leftButtonsPane, java.awt.BorderLayout.WEST);

        rightButtonsPanel.setName("rightButtonsPanel"); // NOI18N
        rightButtonsPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        CloseButton.setText(resourceMap.getString("CloseButton.text")); // NOI18N
        CloseButton.setName("CloseButton"); // NOI18N
        CloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonClicked(evt);
            }
        });
        rightButtonsPanel.add(CloseButton);

        buttonspanel.add(rightButtonsPanel, java.awt.BorderLayout.EAST);

        getContentPane().add(buttonspanel, java.awt.BorderLayout.PAGE_END);

        mainpanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8), javax.swing.BorderFactory.createEtchedBorder()));
        mainpanel.setMaximumSize(new java.awt.Dimension(32767, 174));
        mainpanel.setMinimumSize(new java.awt.Dimension(100, 174));
        mainpanel.setName("mainpanel"); // NOI18N
        mainpanel.setOpaque(false);
        mainpanel.setPreferredSize(new java.awt.Dimension(420, 174));
        mainpanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        internalPanel.setName("internalPanel"); // NOI18N
        internalPanel.setLayout(new java.awt.GridBagLayout());

        findLabel.setText(resourceMap.getString("findLabel.text")); // NOI18N
        findLabel.setName("findLabel"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 0);
        internalPanel.add(findLabel, gridBagConstraints);

        replaceLabel.setText(resourceMap.getString("replaceLabel.text")); // NOI18N
        replaceLabel.setName("replaceLabel"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 0);
        internalPanel.add(replaceLabel, gridBagConstraints);

        findTextfield.setColumns(24);
        findTextfield.setText(resourceMap.getString("findTextfield.text")); // NOI18N
        findTextfield.setName("findTextfield"); // NOI18N
        findTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindTextfieldEnterPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        internalPanel.add(findTextfield, gridBagConstraints);

        replaceTextfield.setColumns(24);
        replaceTextfield.setText(resourceMap.getString("replaceTextfield.text")); // NOI18N
        replaceTextfield.setName("replaceTextfield"); // NOI18N
        replaceTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replaceTextfieldEnterPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        internalPanel.add(replaceTextfield, gridBagConstraints);

        caseSensitiveCheckbox.setText(resourceMap.getString("caseSensitiveCheckbox.text")); // NOI18N
        caseSensitiveCheckbox.setName("caseSensitiveCheckbox"); // NOI18N
        caseSensitiveCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matchCaseCheckboxClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 0);
        internalPanel.add(caseSensitiveCheckbox, gridBagConstraints);

        mainpanel.add(internalPanel);

        getContentPane().add(mainpanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonClicked
        panel.setSearchIsCaseSensitive(oldCaseSensitivitySetting);
        undoableEdit.end();
        gui.getUndoManager().forwardUndoEvents(null);
        if (replacecount>0) {
           gui.getUndoManager().addEdit(undoableEdit);
        }
        setVisible(false);
    }//GEN-LAST:event_closeButtonClicked

    private void ReplaceAllButtonPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReplaceAllButtonPressed
        String searchString=findTextfield.getText();
        if (searchString==null) searchString="";
        if (searchString.isEmpty()) findTextfield.requestFocusInWindow();
        else {
            String replaceString=replaceTextfield.getText();
            if (replaceString==null) replaceString="";
//            if (replaceString.isEmpty()) replaceTextfield.requestFocusInWindow();
//            else {
            replacecount+=panel.replaceAll(searchString,replaceString);
            //}
        }
    }//GEN-LAST:event_ReplaceAllButtonPressed

    private void FindTextfieldEnterPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindTextfieldEnterPressed
        findNextButtonPressed(evt);
    }//GEN-LAST:event_FindTextfieldEnterPressed

    private void replaceTextfieldEnterPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replaceTextfieldEnterPressed
        replaceButtonPressed(evt);
    }//GEN-LAST:event_replaceTextfieldEnterPressed

    private void replaceButtonPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replaceButtonPressed
        String searchString=findTextfield.getText();
        if (searchString==null) searchString="";
        if (searchString.isEmpty()) findTextfield.requestFocusInWindow();
        else {
            String replaceString=replaceTextfield.getText();
            if (replaceString==null) replaceString="";
            if (replaceString.isEmpty()) replaceTextfield.requestFocusInWindow();
            else {
                boolean replaced=panel.replaceCurrent(searchString,replaceString);
                if (replaced) {
                    replacecount++;
                    panel.find(searchString); // find next instance
                }
            }
        }
    }//GEN-LAST:event_replaceButtonPressed

    private void findNextButtonPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findNextButtonPressed
        String searchString=findTextfield.getText();
        if (searchString==null) searchString="";
        if (searchString.isEmpty()) findTextfield.requestFocusInWindow();
        else {
            panel.find(searchString);
        }
    }//GEN-LAST:event_findNextButtonPressed

    private void matchCaseCheckboxClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matchCaseCheckboxClicked
        panel.setSearchIsCaseSensitive(caseSensitiveCheckbox.isSelected());
    }//GEN-LAST:event_matchCaseCheckboxClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseButton;
    private javax.swing.JButton ReplaceAllButton;
    private javax.swing.JPanel buttonspanel;
    private javax.swing.JCheckBox caseSensitiveCheckbox;
    private javax.swing.JLabel findLabel;
    private javax.swing.JButton findNextButton;
    private javax.swing.JTextField findTextfield;
    private javax.swing.JPanel internalPanel;
    private javax.swing.JPanel leftButtonsPane;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JButton replaceButton;
    private javax.swing.JLabel replaceLabel;
    private javax.swing.JTextField replaceTextfield;
    private javax.swing.JPanel rightButtonsPanel;
    // End of variables declaration//GEN-END:variables

}
